# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 09:58
from __future__ import unicode_literals

import blog_pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AddField(
            model_name='post',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=blog_pages.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='post',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
