# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 19:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_pages', '0002_auto_20160803_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 8, 3, 19, 32, 12, 676142, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
